# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: CGO_ENABLED=0 go build -v ./...

    - name: SCP deploy action
      uses: nogsantos/ssh-scp-deploy@v1.3.0
      with:
        src: ./twitter_bot
        host: ${{ secrets.SSH_HOST }}
        remote: ${{ secrets.SSH_DIR }}/twitter_bot_new
        port: ${{ secrets.SSH_PORT }}
        user: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
